### ISSUE TITLE
Doesn't work for non-community tables

### ISSUE THREAD

**Issue by slowernet** [gabrielfalcao/jquery-yql#1]
Hardcoding `env: 'store://datatables.org/alltableswithkeys'` breaks queries on internal Yahoo web services. Thanks.

**Comment by slowernet** [comment]
Sorry, withdrawn. Appears this was a transient problem with YQL.

**Comment by gabrielfalcao** [comment]
:)

**Comment by slowernet** [comment]
I talked this over a bit with http://github.com/sh1mmer in IRC, and he indicated that there may be a bug in http://datatables.org/alltables.env (geo.placemaker is defined there, possibly overriding the core version with a no-op) and also that it's preferable not to load tables you aren't using:

sh1mmer: it's probably a bug
[12:10pm] sh1mmer: I don't think we should have a placemaker table in the community tables
[12:10pm] sh1mmer: but you can fix it by using your own env file
[12:11pm] sh1mmer: which is probably better because you shouldn't really tell yql to load tables you don't need

So ultimately, it might be desirable for the plugin to accept an "env" option, rather than assuming store://datatables.org/alltableswithkeys.

**Comment by slowernet** [comment]
(I would fork and make the change myself, but I didn't want to make assumptions about how you'd want to break or not break the current API.)

**Comment by gabrielfalcao** [comment]
There is a long time I don't even touch this project. I assume that @guilhermechapiewski
is using it, but I'm not sure, so feel free to fork and make your changes, I'll apply them and make a new official release.
