### ISSUE TITLE
Use YQL's native query parameters rather than your own

### ISSUE THREAD

**Issue by spullara** [gabrielfalcao/jquery-yql#4]
In your example you have '#{username}' when you should probably just use @username and then pass the username in as query parameter. This will also make sure that it works with query aliases.

**Comment by gabrielfalcao** [comment]
YQL native parameters + release 0.3. closed by ae55f66380ea5410e18b5df630d50a39e7d9e054

**Comment by spullara** [comment]
I'm not sure you got the spirit of the suggestion. I see that you allow people to use @ for variables but you are still doing client side replacement. Here is an example query that uses YQL @ variables:

http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20search.web%20where%20query%3D%40query&diagnostics=true&query=github

The @query is actually sent to YQL along with a parameter matching the variable name and it is replaced on the server.

**Comment by gabrielnahmias** [comment]
Simply store these in the data object passed to the request.
